id: P000810
initial_creation_type: ocr
created_at: 5/04/2021
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN3438
  title: རྩ་ཤེས་ཀྱི་ཊཱི་ཀ་དང་ཚིག་གསལ་གྱི་དཀའ་གནད་དང་སྤྱི་སྡོམ།
  volumes:
    66b128b8f8aa4cc9b42f94a389034fa4:
      image_group_id: I3CN8574
      title: ''
      base_file: v001.txt
  author: ''
